### ISSUE TITLE
Please support codes with `UTF-8 BOM` encoding

### ISSUE THREAD

**Issue by psychelzh** [jdneo/vscode-checkstyle#141]
When processing style checking for `java` source files with `UTF-8 BOM` encoding, the following error occurred. It could not recognize the `BOM` at the front of the characters.

```java
Checkstyle Error: - 'Command failed with exit code: 4294967294. Stderr: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing c:\Users\liang\OneDrive\Documents\Git\iquizoo\Iqmethod\test\src\test\java\com\iquizoo\server\world\common\tool\EvaluationTool.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:430)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:362)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:177)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file c:\Users\liang\OneDrive\Documents\Git\iquizoo\Iqmethod\test\src\test\java\com\iquizoo\server\world\common\tool\EvaluationTool.java.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:199)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
	... 4 more
Caused by: c:\Users\liang\OneDrive\Documents\Git\iquizoo\Iqmethod\test\src\test\java\com\iquizoo\server\world\common\tool\EvaluationTool.java:1:1: unexpected token: ﻿package
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:446)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:179)
	... 7 more
'
```

**Comment by jdneo** [comment]
@psychelzh Looks like the Checkstyle jar itself cannot recognize the `UTF8 BOM` encoding. 

Have you tried calling Checkstyle command line directly to see the result?

**Comment by jdneo** [comment]
Closing this issue since the extension has been rewritten from `1.0.0`, the core mechanism has been changed.

@psychelzh If you meet any new problems, please feel free to open issues to let us know.

Thanks.
