### ISSUE TITLE
Checkstyle does not work depending on .project settings

### ISSUE THREAD

**Issue by jakegt1** [jdneo/vscode-checkstyle#169]
When running checkstyle, the result in the checkstyle output is always an empty object, and all I have noticed that there is a NullPointerException in the Java Language Server output:

```
[Error - 03:40:23] 20-Mar-2019 03:40:23 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
	at com.shengchen.checkstyle.runner.CheckstyleRunner.check(CheckstyleRunner.java:63)
	at com.shengchen.checkstyle.runner.handler.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:37)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:455)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$30(JDTLanguageServer.java:821)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)

[Error - 03:40:23] 20-Mar-2019 03:40:23 Error in calling delegate command handler
null
java.lang.NullPointerException
	at com.shengchen.checkstyle.runner.CheckstyleRunner.check(CheckstyleRunner.java:63)
	at com.shengchen.checkstyle.runner.handler.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:37)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:455)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$30(JDTLanguageServer.java:821)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)
```

It seems to me that this is due to [Line 63 of CheckstyleRunner.java](https://github.com/jdneo/vscode-checkstyle/blob/master/jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleRunner.java#L63), which isn't checking whether the project exists or not (or that the charset returned is null).

**Comment by jdneo** [comment]
@jakegt1 Thank you for reporting the issue.

What kind of project you are working on? I'm curious the root cause of the null project.

**Comment by jakegt1** [comment]
It's a Gradle project, and i only have the default .project files created by the redhat java plugin.

To me it doesn't seem particularly obvious from the project file why this wouldn't work, but i don't know much about .project files nor the eclipse java libraries.

**Comment by jdneo** [comment]
@jakegt1 Is it possible for you to share the project to me?

**Comment by jakegt1** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>proj-name</name>
	<comment>Project proj-name created by Buildship.</comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
	</natures>
</projectDescription>
```

**Comment by jdneo** [comment]
@jakegt1 Thank you for sharing.

Well, actually I mean the project, not the `.project` file. 😄 

Would you mind to share? It's ok if don't want to cuz I understand some project may contain some private contents.

**Comment by jakegt1** [comment]
I cannot share the project, sorry. for what it's worth, it's using Gradle 1.12 (old i know) and otherwise is a pretty standard java project.

**Comment by jdneo** [comment]
@jakegt1 Hmm, Is the `Language Support for Java` works well on your project? In other word, is there any errors in the `Problems` panel?

**Comment by jakegt1** [comment]
I do have an error to do with gradle version, but oddly if i open a file *outside* of the project area.. checkstyle works fine, even with the problem.

**Comment by jakegt1** [comment]
So, part of this bug is probably related to this (https://github.com/redhat-developer/vscode-java/issues/875), but i still note that i first had the weird problem with .project before having any issue with gradle version.

Still can't really provide something really reproducible, so sorry about that.

**Comment by jdneo** [comment]
@jakegt1 Thank you for the information. Let's see if the problem could be resolved if https://github.com/redhat-developer/vscode-java/issues/875 get fixed

**Comment by jdneo** [comment]
Is the problem been solved after using the newest `Language Support for Java`?

**Comment by jakegt1** [comment]
I'll close it - seems fine now. I think this might ocasionally happen if the language server causes bad files (just need to clean workspace and restart.)

**Comment by jdneo** [comment]
@jakegt1 Thank you for providing the workaround.
