### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by NielsKIT** [jdneo/vscode-checkstyle#173]
Checkstyle does not work in my maven Project. Java Version 11 is written down in the pom.xml

If i open a folder from the Project everxthing works just fine, only if i Open the Workspace or project at once there is an error.

i read some bugs and tried java 8 without success

CHeckstyle output: {}  
nothing more

java language support output:
[Error - 14:48:59] 20.05.2019, 14:48:59 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
	at com.shengchen.checkstyle.runner.CheckstyleRunner.check(CheckstyleRunner.java:63)
	at com.shengchen.checkstyle.runner.handler.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:37)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$35(JDTLanguageServer.java:847)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[Error - 14:48:59] 20.05.2019, 14:48:59 Error in calling delegate command handler
null
java.lang.NullPointerException
	at com.shengchen.checkstyle.runner.CheckstyleRunner.check(CheckstyleRunner.java:63)
	at com.shengchen.checkstyle.runner.handler.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:37)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$35(JDTLanguageServer.java:847)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

system Information:

CPUs | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.85GB (11.78GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by NielsKIT** [comment]
Now it works

Pom cleared and java language server cleared and new entry in workspace found.
	"settings": {
		"java.configuration.updateBuildConfiguration": "automatic"
	}

pom before:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  
  <parent>
      <groupId>edu.kit.ipd.swt1.ss2019</groupId>
      <artifactId>uebungsparent</artifactId>
      <version>0.0.1-SNAPSHOT</version>
  </parent>


  <groupId>swt1</groupId>
  <artifactId>iMage</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>iMage</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <repositories>
    <repository> <id>ipdNexus</id> <url>http://bob.ipd.kit.edu/nexus/repository/maven-public-all/</url>
    </repository>
  </repositories>
  <modules>
    <module>iMage.HDrize.base</module>
  </modules>
</project>


pom now:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  
  <parent>
      <groupId>edu.kit.ipd.swt1.ss2019</groupId>
      <artifactId>uebungsparent</artifactId>
      <version>0.0.1-SNAPSHOT</version>
  </parent>


  <groupId>swt1</groupId>
  <artifactId>iMage</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>iMage</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>


  <repositories>
    <repository> <id>ipdNexus</id> <url>http://bob.ipd.kit.edu/nexus/repository/maven-public-all/</url>
    </repository>
  </repositories>
  <modules>
    <module>iMage.HDrize.base</module>
    <module>iMage.HDrize</module>
  </modules>
</project>
