### ISSUE TITLE
Dont know how to setup plug-in

### ISSUE THREAD

**Issue by BigSamu** [jdneo/vscode-checkstyle#307]
Hi, 

Do you have any instructions for setting up the plug-in? I am unable to make it run in VSCode. I am using macOS Catalina 10.15.7 and VSCode 1.52.1. Also, I have already installed the Language Support for Java by RedHat.

Regards,

Samuel

**Comment by jdneo** [comment]
Have you set the VS Code setting: `java.checkstyle.configuration` & `java.checkstyle.version`?

**Comment by gabipetrovay** [comment]
I have a similar issue with the latest versions of vscode, extension, and checkstyle on Mac.

* the extension is installed without errors
* the actions are available in VScode (set configuration, check code) in context menus and `command-3` (Mac)
* the configuration options are available (in user, workspace, folder)
* I provided the `${workspaceFolder}/path/to/checkstyle/checks.xml` and version `8.40` for in all setting scopes.
* the user settings have the additional setting for automatic checks (enabled)
* in the command line this checkstyle configuration shows a few errors

In VSCode no Problems markers are visible/set. :(

**Comment by jdneo** [comment]
@gabipetrovay Is there any output in the dev console?

You can check it by `Help > Toggle Developer Tools` and see if there is any suspicious output.

**Comment by gabipetrovay** [comment]
No errors are show (for this extension) in Developer Tools while editing the code or invoking the Checkstyle actions.

Only while changing the version in the workbench JSON settings (from default to `8.40`), the following 2 errors appear:
```
{
  message: '[Error - 8:56:41 AM] 25 Feb 2021, 08:56:41 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".\n' +    'null\n' +    'java.lang.reflect.InvocationTargetException\n' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\n' +    '\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n' +    '\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\n' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)\n' +    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)\n' +    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)\n' +    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n' +    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\n' +    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)\n' +    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\n' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: /Users/taapega4/Work/bar/ibis-parent/ibis-parent/ibis-ci-tools/checkstyle/checks.xml\n' +    '\tat com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:528)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:265)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:244)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:211)\n' +    '\tat com.shengchen.checkstyle.checker.CheckerService.setConfiguration(CheckerService.java:67)\n' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:79)\n' +    '\t... 17 more\n',
  level: 'info',
  timestamp: '2021-02-25 08:56:41.310'
}
```

```
{
  message: '[Error - 8:56:41 AM] 25 Feb 2021, 08:56:41 Error in calling delegate command handler\n' +    'null\n' +    'java.lang.reflect.InvocationTargetException\n' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\n' +    '\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n' +    '\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\n' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)\n' +    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)\n' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)\n' +    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)\n' +    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n' +    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\n' +    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)\n' +    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)\n' +    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\n' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: /Users/taapega4/Work/bar/ibis-parent/ibis-parent/ibis-ci-tools/checkstyle/checks.xml\n' +    '\tat com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:528)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:265)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:244)\n' +    '\tat com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:211)\n' +    '\tat com.shengchen.checkstyle.checker.CheckerService.setConfiguration(CheckerService.java:67)\n' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:79)\n' +    '\t... 17 more\n',
  level: 'info',
  timestamp: '2021-02-25 08:56:41.330'
}
```

**Comment by jdneo** [comment]
I saw: ` Unable to find: /Users/me/Work/bar/ibis-parent/ibis-parent/ibis-ci-tools/checkstyle/checks.xml`

**Comment by gabipetrovay** [comment]
I fixed this (removed duplicate directory in path) and still no checkstyle errors are visible. The problem was from the expansion of the `workspaceFolder` variable:

```
${workspaceFolder}/ibis-ci-tools/checkstyle/checks.xml
```

became:

```
```
${workspaceFolder}/ibis-parent/ibis-ci-tools/checkstyle/checks.xml
```

**Comment by gabipetrovay** [comment]
Even with a correct path the following errors are thrown (in Developer Tools). 2 errors each time the file is saved (with a correct or wrong path, always the same):

```
[Error - 3:30:46 PM] 25 Feb 2021, 15:30:46 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/api/AuditListener
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3296)
	at java.base/java.lang.Class.getConstructor0(Class.java:3501)
	at java.base/java.lang.Class.getConstructor(Class.java:2244)
	at com.shengchen.checkstyle.runner.CheckstyleLoader.loadCheckerService(CheckstyleLoader.java:49)
	at com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:75)
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.api.AuditListener
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more
```

and

```
[Error - 3:30:24 PM] 25 Feb 2021, 15:30:24 Error in calling delegate command handler
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/api/AuditListener
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3296)
	at java.base/java.lang.Class.getConstructor0(Class.java:3501)
	at java.base/java.lang.Class.getConstructor(Class.java:2244)
	at com.shengchen.checkstyle.runner.CheckstyleLoader.loadCheckerService(CheckstyleLoader.java:49)
	at com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:75)
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.api.AuditListener
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more
```

**Comment by gabipetrovay** [comment]
🎆 I managed to make it work! But it looks like a configuration reading issue:

* With the default version (`8.18`) in the **User** settings and the configuration file in the **Workspace** settings it always shows the above posted errors.
* When I explicitly write the default version (`8.18`) in the **Workspace** settings, it starts to throw (also in the Developer Tools instead of the Output view) errors about unsupported features used in the XML file but not available in the default version.
* Then I started to choose different versions (e.g. `8.40`) and still had unusported Checkstyle issues: [`COMPACT_CTOR_DEF`](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#COMPACT_CTOR_DEF) even though this is available since version `8.36`. Also running in the command line Checkstyle with the release `8.40` downloaded from Github, it works correctly.

So questions:
* what can be the issue that the version is not inherited from the **User** settings? (when the configuration is specified in the **Workspace** settings)
* Where is Checkstyle downloaded from? The Github version `8.40` supports `COMPACT_CTOR_DEF` while the one in vscode doesn't

**Comment by jdneo** [comment]
> What can be the issue that the version is not inherited from the User settings? (when the configuration is specified in the Workspace settings)

What's the User and Workspace settings look like on your machine?

> Where is Checkstyle downloaded from?

It's download from GitHub Release page: https://github.com/jdneo/vscode-checkstyle/blob/master/src/checkstyleConfigurationManager.ts#L141
