### ISSUE TITLE
Checkstyle starts to fail as soon I use a custom Checkstyle config file

### ISSUE THREAD

**Issue by jersson** [jdneo/vscode-checkstyle#320]
Issue Type: <b>Bug</b>

Hey guys, hope you're doing well, I was using the checkstyle extension and everythin was working well as soon I tried to use a custom file, not sure what the problem is but it's not working even with a copy for a known style definition (I put the google file on my repo)

The error I got is:
```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:120745)
	at async Object.syncServer (/Users/Jersson_Dongo/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:81077)
	at async Object.refresh (/Users/Jersson_Dongo/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:79786)
	at async Object.initialize (/Users/Jersson_Dongo/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:77932)
	at async g (/Users/Jersson_Dongo/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:29:20243)
```

Here's the repo/commit you can check my code sample: https://github.com/jersson/demo-spring-service/tree/542f03a9a2883cc0381e23a40ba7c6027d9ceec4

Thanks in advance, 
JD

Extension version: 1.4.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|64.00GB (8.33GB free)|
|Process Argv|. --crash-reporter-id 446147ab-1c4d-4010-9607-ceecc65ccd1d --crash-reporter-id 446147ab-1c4d-4010-9607-ceecc65ccd1d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by lvicentesanchez** [comment]
Same for me.

**Comment by lvicentesanchez** [comment]
And I just solved this problem by updating the checkstyle version to 8.41 (the same version I have in my pom)
