### ISSUE TITLE
Checkstyle reliably fails with Remote Host (Windows + WSL Ubuntu)

### ISSUE THREAD

**Issue by leogott** [jdneo/vscode-checkstyle#321]
I'm trying to use checkstyle with Windows 10 + WSL2 and Ubuntu LTS 18.04

I reset all settings to default and then used "> Checkstyle: Set the Checkstyle Configuration File" to select the built-in google config. Then I used the context menu on an open file to run checkstyle on it.
I didn't see anything happen and checked the Output Panel to see that the checkstyle plugin had run into an issue:
```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
	at _executeContributedCommand (/home/ela/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:85:109411)
	at async Object.syncServer (/home/ela/.vscode-server/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:81015)
	at async Object.refresh (/home/ela/.vscode-server/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:79724)
```

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by karthik20** [comment]
The same for me as well. It fails in both WSL as well as Remote-SSH with/without built in style configs. I'm yet to try on local Windows without remote.

**Comment by adtani** [comment]
Same issue noticed

**Comment by WtfJoke** [comment]
Its also reproducable in Github Codespaces (e.g the exctension cant be used there as well) and can be reproduced with the currently latest version 1.4.1

```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
    at l._executeContributedCommand (/vscode/bin/linux-x64/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/server/remoteExtensionHostProcess.js:94:111812)
    at Object.syncServer (/home/codespace/.vscode-remote/extensions/shengchen.vscode-checkstyle-1.4.1/dist/extension.js:1:82761)
    at Object.refresh (/home/codespace/.vscode-remote/extensions/shengchen.vscode-checkstyle-1.4.1/dist/extension.js:1:81470)
```

**Comment by jdneo** [comment]
I tried the extension in GitHub Codespaces today, it works fine on my side

![image](https://user-images.githubusercontent.com/6193897/141082184-7273bd61-719b-4fac-921a-1e4acb400449.png)

Haven't tried with Remote extensions, but AFAIK, if Codespaces works, Remote should work as well. 🤔

**Comment by leogott** [comment]
Lmk if there's anything I can try to help pin down the issue.
There aren't any convenient alternatives to using this plugin so I'd like to get this working

**Comment by leogott** [comment]
Oh, I got it working now!
VSCode 1.63.2
Checkstyle 1.4.1

Looks like the underlying problem was fixed in the meantime. It didn't work earlier because of a different problem that was easy to work around. I opened a new issue for it #327
